### ISSUE TITLE
Confusing Mock Data

### ISSUE THREAD

**Issue by Chris-Greaves** [Thomas-Engineering/technical-tests#1]
The candidate-data.json mock file is a little confusing because it seems that the `assessments` property on a candidate contains an array of objects containing two assessments.

Below is a cut down example of the `assessments` property and what it contains:

```json
{
    . . .
    "assessments": [
        {
            "aptitude": {
                "sentOn": "04/03/2020",
                . . .
            },
            "behaviour": {
                "sentOn": "11/03/2020"
            }
        }
    ]
}
```

If you look at the value of the array its an object with two properties, `aptitude` and `behaviour`:

```json
{
    "aptitude": {
        "sentOn": "04/03/2020",
    },
    "behaviour": {
        "sentOn": "11/03/2020"
    }
}
```

Is an assessment the combination of aptitude and behaviour, or is this meant to be a list like this

```json
{
    . . .
    "assessments": [
        {
            "assessment-type": "aptitude",
            "sentOn": "04/03/2020",
            . . .
        },
        {
            "assessment-type": "behaviour",
            "sentOn": "11/03/2020"
        }
    ]
}
```

This is the part that is confusing, because its not clearly defined what an assessment is. If its meant to be a list containing either behaviour or aptitude assessments, then an example would be like such:

```json
{
    "id": "ce66aa53-e571-4d98-a004-d73b4cad37d8",
    "firstname": "Emylee",
    "surname": "Woodson",
    "assessments": [
        {
            "assessment-type": "aptitude",
            "sentOn": "04/03/2020",
            "completedOn": "18/03/2020",
            "trainabilityIndex": 34
        },
        {
            "assessment-type": "behaviour",
            "sentOn": "11/03/2020"
        }
    ]
}
```

**Comment by jRawling** [comment]
There are 4 assessments in total (only 2 of which are represented in the mock-data), all of which are very different in their full views (and have different properties), rather than these simplified versions. From a backend perspective, I see them all as children of Assessment if you like to think in inheritance terms.

An example taken from the mock-data:

`"assessments": [
           {
               "aptitude": {
                   "sentOn": "04/03/2020",
                   "completedOn": "08/03/2020",
                   "trainabilityIndex": 20
               },
               "behaviour": {
                   "sentOn": "10/03/2020",
                   "completedOn": "17/03/2020",
                   "workingStrengths": "D"
               }
           }
       ]`

I could have just made the assessments props for the root object (with nulls if they didn't take it). I suppose in this instance my reasoning is there could be several Behaviour assessments (as from a domain point of view, this changes over time and people regularly retake this assessment.

How data is presented at the front doesn't have to relate to how it's stored / managed in the back. At the end of the day, implement it how you like, it's all good discussion in an interview. :)

Does that clear things up?

**Comment by Chris-Greaves** [comment]
I guess the last question I have around the JSON is what do you expect the JSON to look like if someone re-took an aptitude test for example?

**Comment by jRawling** [comment]
Had a chat with the team and you're right, it's a bit all over the place and I've preempted things that don't need preempting. Expect to see an update to the mock JSON shortly. :)
